[font]
size = 12
[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[terminal.shell]
program = "wsl.exe"
args = ["-d", "NixOS", "--cd", "~", "nu"]

[window]
opacity = 0.95
padding = { x = 20, y = 20 }
dimensions = { columns = 120, lines = 30 }
blur = true

[terminal]
